### ISSUE TITLE
Asignaciones

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs-es/vuejs.org#2]
Quién se anima a traducir la API?

**Comment by zgudino** [comment]
✋ yo! La doc API se puede fragmentar "secciones" en tareas. Ejemplo,
- [ ] Traducir _Global Config_
- [ ] Traducir _Global API_
...

**Comment by miljan-aleksic** [comment]
Me he dado cuenta que no es necesario crear tickets para el Project, pero se pueden convertir las tarjetas creadas en el mismo a Ticket. Por lo que de momento empezemos asignando las secciones como tarjetas y si es necesario ya las convertiremos a tickets después.

**Comment by zgudino** [comment]
@miljan-aleksic tienes razón! Wow eso es nuevo 😃
 
![screen shot 2016-12-05 at 2 52 41 am](https://cloud.githubusercontent.com/assets/14242895/20877346/029c4150-ba96-11e6-98d2-3e07fe2c07fc.png)

**Comment by miljan-aleksic** [comment]
Sí! Parece útil :)

Ya he creados las tarjetas de todas las Secciones Essentials. A ver quién más se anima y vamos asignando. Si alguna sección se hace larga, la podemos dividir.

**Comment by coderdiaz** [comment]
Que tal a todos compañeros, no sería bueno que tuvieramos integrado [Gitter ](https://gitter.im/) con este proyecto para así estar comunicados y poder platicar de mejor manera acerca de este gran proyecto que se esta emprendiendo?

Saludos.

**Comment by miljan-aleksic** [comment]
A mi me parecen bien, siempre y cuando para temas concretos o importantes sigamos usando los tickets, tanto por organizacion como por evidencia.

**Comment by coderdiaz** [comment]
@miljan-aleksic Tu lo generas?

**Comment by miljan-aleksic** [comment]
Listo :)

**Comment by initdav** [comment]
Disculpenme. Traduje los contenidos de src/v2/examples sin que esta estuviera asignada a mi -hace poco descubrí Vue.js, me encantó y hoy supe que existía esta iniciativa para traducir los contenidos del sitio a Español-, espero que no haya ningún problema si este estaba asignado a alguien más, sientanse en libertad de declinar mi PR si es necesario.

Espero poder colaborar con traducir más secciones si es posible.

**Comment by miljan-aleksic** [comment]
Hola David! Tranquilo, no pasa nada, aunque para la próxima avísanos y así evitamos duplicar trabajo. Te ha asignado la sección y te invito a que te leas las [pautas de colaboración](https://github.com/vuejs-es/vuejs.org/wiki/CONTRIBUTING), revises la traducción acorde y cuando lo creas oportuno nos pidas revisión.

Muchas gracias y que sepas que también estamos en [Gitter](https://gitter.im/vuejs-es/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by zeratulmdq** [comment]
Buenas!

Creo que para que quede un poco más ordenado todo, se debería empezar por el principio (valga la redundancia). Por lo que me apunto para empezar a traducir _Installation_. Una vez que lo vea asignado en el proyecto, comienzo con el trabajo.

Saludos!

**Comment by coderdiaz** [comment]
@zeratulmdq Claro que si, en cuanto @miljan-aleksic te indique :)

**Comment by miljan-aleksic** [comment]
@zeratulmdq, ya lo tienes asignado ;)

**Comment by coderdiaz** [comment]
@zeratulmdq no olvides participar en el chat grupal en [Guitter](https://gitter.im/vuejs-es/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by panietoar** [comment]
Quisiera trabajar en "Computed Properties and Watchers"

**Comment by miljan-aleksic** [comment]
Ya lo tiene asignado @panietoar. Cuando lo tengas listo para revisión create un Pull Request.

**Comment by panietoar** [comment]
Listo
https://github.com/vuejs-es/vuejs.org/pull/9/files

**Comment by panietoar** [comment]
Bueno, mientras revisan el de Computed and Watchers, iré trabajando en "Class and Style Bindings".
@miljan-aleksic para la asignación. Gracias

**Comment by panietoar** [comment]
Listo el PR de la sección de estilos y clases:

https://github.com/vuejs-es/vuejs.org/pull/10

**Comment by miljan-aleksic** [comment]
@panietoar, tus cambios me parecieron bien. Ya está aceptado todo, muchas gracias :)

**Comment by panietoar** [comment]
Ahora tomaré Conditional Rendering

**Comment by panietoar** [comment]
PR listo:
https://github.com/vuejs-es/vuejs.org/pull/11

**Comment by panietoar** [comment]
@miljan-aleksic Mientras tanto empiezo con List Rendering

**Comment by panietoar** [comment]
Listo el PR de List Rendering
https://github.com/vuejs-es/vuejs.org/pull/12

**Comment by panietoar** [comment]
Creo que toca tomar los que están en traducción. Veo que no han recibido actualizaciones en mucho tiempo. Y sería bueno ver ese swimlane bien limpio jaja.

**Comment by miljan-aleksic** [comment]
Estoy deacuerdo :) Terminemos antes las dos secciones que quedan de Essentials. Mientras voy a preguntar a ver si por casualidad han avanzado algo.

**Comment by panietoar** [comment]
Listo Miljan, puedes asignarme las dos de essentials que quedan entonces.

**Comment by miljan-aleksic** [comment]
Qué crack, hecho :)

@jstoledano , @juanda95 , @lmdrx , @zgudino , @coderdiaz , @fergthh : si habéis avanzado algo, aunque esté a medias, por favor cread un PR, lo revisamos y ya lo termina Pablo o quien tenga tiempo. Por favor informar para que podamos seguir avanzando. Gracias de todos modos!

**Comment by miljan-aleksic** [comment]
@panietoar, viendo que nadie comenta nada he liberado todas las secciones pendientes y te he asignado "The Vue instance" para cuando puedas. Si prefieres otra sección, dimelo.

**Comment by panietoar** [comment]
Esa está bien

**Comment by panietoar** [comment]
PR de la sección instancia:
https://github.com/vuejs-es/vuejs.org/pull/15

**Comment by miljan-aleksic** [comment]
Gracias :) Adjudicate siguiente la que quieras.

**Comment by panietoar** [comment]
Continuaré con Introduction y luego con Components.

**Comment by panietoar** [comment]
PR de Intruduction:
https://github.com/vuejs-es/vuejs.org/pull/16

**Comment by panietoar** [comment]
Finalmente!!!! La sección componentes:
https://github.com/vuejs-es/vuejs.org/pull/17

jajajaja

**Comment by miljan-aleksic** [comment]
Te entiendo, tardé lo suyo tan solo revisando :)

**Comment by panietoar** [comment]
Siguientes:

Transition Effects
Option Data

**Comment by panietoar** [comment]
PR para Transiciones:
https://github.com/vuejs-es/vuejs.org/pull/19

Y una corrección a la instalación:
https://github.com/vuejs-es/vuejs.org/pull/18

**Comment by panietoar** [comment]
@miljan-aleksic La sección Option Data no la encontré en /v2/guide. Creo que se refiere a la sección option / data de /v2/api.

Así que la dejo para después cuando empecemos con dicha sección.

Para terminar essentials, voy a traducir Template Syntax.

**Comment by panietoar** [comment]
PR de Sintaxis de Plantilla:
https://github.com/vuejs-es/vuejs.org/pull/21

**Comment by miljan-aleksic** [comment]
@panietoar, cuando terminemos con las secciones basicas haré un sync con la repo original, ya que me parece han actualizado la estructura y quizás cambiado algo.

Habrá que revisarlo bien, por lo que no comiences ninguna traducción de las otras secciones.

**Comment by panietoar** [comment]
Bueno, Global Config y Global API

**Comment by panietoar** [comment]
@miljan-aleksic Global Config ya está traducido en master.
Cerremos ese ticket y yo continúo con Global API

**Comment by miljan-aleksic** [comment]
@panietoar, fijate bien por que parece que solo está traducido el principio.

**Comment by panietoar** [comment]
Ajam, está todo en un solo archivo, ambas secciones están dentro de /v2/api/index.
De modo que continúo con Global API en el mismo archivo.

**Comment by panietoar** [comment]
PR de Global API:
https://github.com/vuejs-es/vuejs.org/pull/22

Con nota especial

**Comment by miljan-aleksic** [comment]
Gracias @panietoar. Ya lo he revisado, parece que hay secciones sin traducir?

**Comment by coderdiaz** [comment]
Algo en lo que les pueda ayudar, había estado un poco atareado.

Saludos.

**Comment by miljan-aleksic** [comment]
@coderdiaz, ya estamos terminando los Essentials, cuando esté listo y hayamos actualizado la base con los últimos cambios de la versión en Inglés, podríamos entre todos revisarlo. Ya avisaré.

**Comment by panietoar** [comment]
@miljan-aleksic PR para la sección Options / DOM:

https://github.com/vuejs-es/vuejs.org/pull/23

**Comment by panietoar** [comment]
@coderdiaz Todas las secciones de la guía avanzada están disponibles para traducir.
Yo estoy traduciendo /v2/api.

En https://github.com/vuejs-es/vuejs.org/projects/1 en el swimlane de Advanced están todas las tareas disponibles. Escoge cualquiera.

**Comment by panietoar** [comment]
@miljan-aleksic PR con lo último de la sección de Opciones:

https://github.com/vuejs-es/vuejs.org/pull/24

**Comment by miljan-aleksic** [comment]
Gracias @panietoar, ya está corregido y aceptado. De los Essentials queda algo o ya lo tenemos todo?

**Comment by panietoar** [comment]
Ya está todo. De /v2/guide sólo falta la parte de advanced.

**Comment by taro-0** [comment]
Hola a todos, me gustaria involucrarme en la traducción ha algo en lo que pueda ayudarles?

**Comment by miljan-aleksic** [comment]
Bienvenido @t4r0, ya está el branch master actualizado con los últimos cambios. 

El trabajo lo dividimos en dos mayores partes, Essentials y Advanced, que són las dos grandes secciones de la documentación. El Essentials se tradujo antes de la syncro, por lo que haría falta revisarlo de nuevo. El Advanced está por traducir.

En [Projects](https://github.com/vuejs-es/vuejs.org/projects/1) puedes elegir en qué seccion trabajar.

@panietoar, tu eres ya un veterano, ya me dirás que asignaciones quieres :)

Gracias chicos!

**Comment by panietoar** [comment]
@miljan-aleksic Gracias.

Yo voy a continuar traduciendo el API.
básicamente el archivo /v2/api/index.md

Voy a hacerlo por secciones. Ya iré creando los PRs

**Comment by panietoar** [comment]
@miljan-aleksic Creo q el kanban se dañó, sale en To Be Assigned todo lo que habíamos traducido.

**Comment by miljan-aleksic** [comment]
@panietoar, no se dañó, lo moví todo yo ya que se tienen que revisar todas las secciones de nuevo.

**Comment by panietoar** [comment]
D:

Ok

**Comment by nikoz84** [comment]
Como va la traduccion?? se necesita ayuda aun??

**Comment by miljan-aleksic** [comment]
@nikoz84, sí - https://github.com/vuejs-es/vuejs.org/issues/2#issuecomment-336314734

**Comment by Tommytrg** [comment]
Buenas, me gustaría comenzar a contribuir en la traducción. @miljan-aleksic puedes asignarme "Reactivity in Depth" ?

**Comment by miljan-aleksic** [comment]
@Tommytrg, hecho :)

**Comment by panietoar** [comment]
PR de la siguiente sección de /v2/api:

https://github.com/vuejs-es/vuejs.org/pull/28

**Comment by miljan-aleksic** [comment]
@panietoar, me llegan todas las notificaciones, sobre todo de los PR, no es necesario avisar ;)

**Comment by panietoar** [comment]
jaja ok

**Comment by jamesxv7** [comment]
Me gustaría colaborar, he realizado aportaciones a la documentación de [Redux en español](https://github.com/sergiodxa/redux-in-spanish/graphs/contributors) (lo menciono como referencia), además trato de escribir sobre el tema en mi [blog](https://www.jaimeolmo.com).

**Comment by miljan-aleksic** [comment]
Toda colaboración es bienvenida @jamesxv7. Qué sección te gustaría traducir?

**Comment by jamesxv7** [comment]
Single File Components?

**Comment by miljan-aleksic** [comment]
@jamesxv7, hecho :)

Cuando lo tengas listo create un PR y si por cualquier razón tienes que desistir, dinoslo para reasignarlo.

**Comment by jamesxv7** [comment]
Vale @miljan-aleksic, ya estoy trabajándolo, me tomará un poco mas de lo normal pues estoy en medio de una situación particular.

**Comment by Tommytrg** [comment]
@miljan-aleksic, podrías asignarme "Transitioning State"?

**Comment by miljan-aleksic** [comment]
@Tommytrg, hecho ;)

**Comment by tochoromero** [comment]
Necesito algunas asignaciones largas, el día de mañana voy a tener un vuelo muy largo y quiero aprovecharlo para traducir.

**Comment by miljan-aleksic** [comment]
@tochoromero, vale, lo reviso y te contesto en breve.

**Comment by miljan-aleksic** [comment]
@tochoromero, te he asignado varias secciones, están todas en Projects bajo columna con tu nombre. Traduze lo que puedas y si se qued algo pendiente, ya lo reasignamos sin problema.

Mañana reviso tus PR recientes. Gracias!!

**Comment by ghost** [comment]
@miljan-aleksic Tal vez puedo ayudar tambien?

**Comment by miljan-aleksic** [comment]
@miguelsolano, te he asignado "Comparison with Other Frameworks". Es largo, pero haz lo que puedas y no te olvides de consultar las Pautas de Traducción en el Wiki.

**Comment by ghost** [comment]
@miljan-aleksic Muchas gracias!

**Comment by UchihaCFC** [comment]
@miljan-aleksic WoW hace tiempo que quiero contribuir pero no había visto este repo n,n! Queda algo que se pueda hacer? ;)

**Comment by miljan-aleksic** [comment]
@UchihaCFC, te he asignado https://github.com/vuejs-es/vuejs.org/projects/1#card-8540005

Sigue las [pautas](https://github.com/vuejs-es/vuejs.org/wiki/Pautas-de-Traducci%C3%B3n) y gracias!

**Comment by UchihaCFC** [comment]
Gracias! forkeo y me pongo

**Comment by miljan-aleksic** [comment]
@UchihaCFC, @miguelsolano, indicarme por favor el estado de las traducciones y si no teneis tiempo para seguir, poder reasignarlo.

@tochoromero, a ti te habia asignado varias secciones, dime en cual de ellas estás trabajando para que las demás las reasigne.

**Comment by UchihaCFC** [comment]
@miljan-aleksic yo voy mas o menos por la mitad de las migraciones, pero quería subirlo todo junto de un golpe, mi intención era acabar este fin de semana (sobretodo puedo ponerme los fines de semana), pero me he puesto a trastear con algunas cosas nuevas de Vue. ¿Va bien si lo subo entre la semana siguiente y máximo la otra?

**Comment by miljan-aleksic** [comment]
Sin problema @UchihaCFC. Gracias :)

**Comment by rgomez90** [comment]
Muy buenas, necesitais algo de ayuda con las traducciones? 
Entré en el proyecto, pero parecen todas asignadas y no hay movimiento desde Mayo...

**Comment by miljan-aleksic** [comment]
@UchihaCFC, @tochoromero si teneis algun progreso hecho, ni que sea parcial, haced un PR. De lo contrario voy a designar vuestras secciones.

@rgomez90, a parte de terminar lo traducido habria que sincronizar la repo de la version en Ingles con esta, ya que han habido muchos cambios. Quizas lo mejor sea crear un nuevo branch con lo ultimo de la version en Ingles (sin traducir) e ir aplicando manualmente, seccion por seccion, lo que ha sido traducido. Si te ves dispuesto puedo preparar dicha repo y guiarte.

**Comment by UchihaCFC** [comment]
@miljan-aleksic yo tengo casi la mitad de la sección designada y la semana que viene podría subir la otra mitad. Ahora mismo no estoy en casa, pero mañana puedo subir lo que hay hecho a más tardar el Lunes en un PR, tenía la idea de subirlo de golpe pero ... me ha faltado algo de tiempo para terminarlo y darle un repaso general.

**Comment by rgomez90** [comment]
@miljan-aleksic yo vine para ayudar, y ahora tengo bastante tiempo (vacaciones) asi q creo que no seria problema.

Por mi, empezamos cuando quieras :)

**Comment by juansaab** [comment]
@miljan-aleksic por acá también me pongo disponible para traducir cualquier página. Me di cuenta que ya tienes asignadas todas las secciones, pero si es que se quedaron en proceso, me gustaría contribuir.

**Comment by miljan-aleksic** [comment]
Hola @juansaab, si quieres puedes ayudarnos con la revision de los PR existentes, que son de la API y Guide. Si @rgomez90 o @UchihaCFC necesitan de ayuda en la traduccion de las mismas, podrian decirnos que parte asignarte.

Una vez terminemos esas dos secciones seguiremos con las demas. Asegurate de leer el Wiki.

**Comment by rgomez90** [comment]
Hola @juansaab yo ya voy avanzado con la guia, pero deje los dos archivos grandes para el final `migrations` y `transitions`. Si quieres prueba a traducir uno de los dos y haz un PR.

Para ello deberias:
 1. descargar branch master a tu PC - necesitas la carpeta src/v2/guide
 2. hacer un fork de la branch 2.5-es
 3. Si quieres empieca por `transitions` que ya esta traducido en `master` y sólo tendrias que comprobar que todo esta correcto y que no se anadieron cosas en ingles (en caso de haber mas cosas, simplemente traducir)
 4. PR de tu fork 2.5-es a la branch 2.5-es de este repo
 5. Cuando se acepte tu PR no olvides de hacer un rebase de tu fork, para actualizar tu repo.

Si a @miljan-aleksic le parece bien, podemos hacerlo así.

**Comment by miljan-aleksic** [comment]
Si, me parece bien, solo remarcar que lo estamos haciendo asi por que Guide ya fue traducido, pero hubieron muchos cambios en la version en Ingles y para asegurarnos que esta todo bien, estamos moviendo lo todo del branch master al 2.5-es. Si es confuso, abre un issue y te ayudamos.

**Comment by juansaab** [comment]
@rgomez90 @miljan-aleksic ya está listo transitions en el Pull Request https://github.com/vuejs-es/vuejs.org/pull/57 Revisé los últimos commits del repositorio oficial para dejarlo al día. Procedo ahora con migrations.

**Comment by miljan-aleksic** [comment]
@juansaab, te dejo instrucciones en el PR.

**Comment by miljan-aleksic** [comment]
@juansaab, @rgomez90, @UchihaCFC, en que punto os encontrais con las traducciones? Si precisais ayuda @IngPaz podria hecha una mano. Si no, en cuanto terminemos las tareas pendientes, contamos contigo para las nuevas.

**Comment by UchihaCFC** [comment]
@miljan-aleksic yo entre hoy-mañana subo correcciones de migrations y sigo con las dos secciones que quedaban de API, imagino que con las pautas nuevas que hemos establecido con esos dos de ahora iré más rápido.

**Comment by juansaab** [comment]
@UchihaCFC ¿tú también estás traduciendo migrations? Yo voy por la línea 600 de ese archivo. Avísame para saber si me detengo y nos coordinamos mejor.

**Comment by UchihaCFC** [comment]
@juansaab perdona quería decir "directives" se me fue la cabeza, yo estoy terminando toda la parte de la sección de api, todo ok si estás con migrations ;)

**Comment by rgomez90** [comment]
@juansaab no te preocupes :) @UchihaCFC esta traduciendo otra parte. 

@miljan-aleksic yo estoy acabando. Tuve dos dias de mucho trabajo y no pude hacer nada. 
Supongo que entre esta noche y manana ya estará todo el guide traducido.

**Comment by siddharta1337** [comment]
Hola @miljan-aleksic  puedes asignarme el Style Guide?
