### ISSUE TITLE
Traducción al español

### ISSUE THREAD

**Issue by dbucci24** [vuejs-es/vuejs.org#32]
Hola, queria saber si quedó algo para traducir, ya que me gustaría colaborar.

**Comment by miljan-aleksic** [comment]
Se agradece toda colaboración. En [projects](https://github.com/vuejs-es/vuejs.org/projects/1) se puede ver el estado actual. Puedes escoger cualquier tema de la columna "por traducir", tan solo avísame para asignartela.

**Comment by dbucci24** [comment]
Puedo traducir cualquiera, asigname las más largas! :)
)

**Comment by miljan-aleksic** [comment]
Vamos por orden, pues. Te he asignado las sección Render Functions. Gracias :)

**Comment by LeoBorai** [comment]
También me gustaria ayudar a traducir la documentación @miljan-aleksic .
De querer traducir algun otro artículo puedo ayudar!

**Comment by miljan-aleksic** [comment]
Te he asignado la sección Custom Directives, @EstebanBorai :)

**Comment by dbucci24** [comment]
Muchas gracias @miljan-aleksic , en estos días comenzaré la traducción!

**Comment by Gonzalo2310** [comment]
@miljan-aleksic Buenas. Me gustaría colaborar en la traducción. Si se puede elegir me gustaría actualizar la parte de cookbook recientemente cambiada en ingles pero si ven que hay algo que halla que hacer anteriormente me parece bien

**Comment by miljan-aleksic** [comment]
Hola @Gonzalo2310, la sección cookbook está en fase beta, por lo que no es buena idea traducirla ahora. Que te parece traducir "State Management" de la sección Advanced?

**Comment by Gonzalo2310** [comment]
Perfecto. Gracias

**Comment by miljan-aleksic** [comment]
Ya lo tienes asignado, gracias a ti :)
