### ISSUE TITLE
Branch Workflow

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs-es/vuejs.org#4]
## Traductores

1. Hacer un fork de este repo
2. Traducir los archivos de la sección asignada
3. Hacer un Pull Request con los cambios

## Organizadores

Según vayamos traduciendo y el main site se vaya actualizando necesitaremos una estrategia para mantener el código al día sin complicarnos la vida. Lo que se suele hacer es lo siguiente:

- Establecer que este fork es `origin` y el repo principal `upstream`.
- Cuando `upstream` tenga alguna actualización aplicarlo al origin con `rebase` (ello nos permite reaplicar nuestros commits siempre por encima manteniendo así el historial limpio).
- Pero al usar `rebase` significa que se cambian los commits y tendremos que forzar el `push`. Si todos trabajamos sobre master será un problema. La solución es trabajar las traducciones en ramas independientes y cuando estén listas aplicarlas al master con fast-forward (asegurándose de aplicar a las mismas los últimos updates del master con rebase).

Puede sonar algo complejo pero es bien sencillo y si hay dudas o sugerencias, ahora es el momento :)

**Comment by zgudino** [comment]
Te parece plasmar este manifesto a `CONTRIBUTING.md`?
:)

**Comment by miljan-aleksic** [comment]
Sí, buena idea. Esperemos los primeros PR a ver si funciona o necesita de ajustes. Ya que probablemente no sea necesario el trabajar en diferentes ramas, tan solo con el master y usando rebase adecuadamente.

**Comment by coderdiaz** [comment]
Ok, en unos días mas estaré enviando mi primer PR. 👍
