### ISSUE TITLE
Como contribuir

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs-es/vuejs.org#46]
1. [Escoge](https://github.com/vuejs-es/vuejs.org/projects/1) una sección sin traducir.
2. [Pide](https://github.com/vuejs-es/vuejs.org/issues/2) su asignación.
3. Haz un fork de este repositorio.
4. Haz la traducción en el fork.
5. Crea un Pull Request con los cambios traducidos.

**Comment by IngPaz** [comment]
Hola me gustaría participar pero veo que todas las secciones ya fueron asignadas, alguna otra opción?

**Comment by miljan-aleksic** [comment]
@ghost, revisa https://github.com/vuejs-es/vuejs.org/issues/68
