### ISSUE TITLE
Revisión General

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs-es/vuejs.org#48]
@rgomez90, gracias por tu disposición. 

La idea es llegar a una version 100% traducida del branch 2.5, que es la version con la que se comenzo esta labor. Por lo que he crado una copia de dicho branch bajo el nombre `2.5-es`. Los pasos a seguir serian:

1. Hacer un fork de esta repo
2. Checkout master y hacer una copia del contenido (solamente carpeta src) en algun lugar fuera de la repo.
3. Checkout 2.5-es, aplicar y revisar archivo por archivo de la carpeta src previamente copiada
4. Subirlo todo a tu repo en gitthub y crear un Pull Request (rgomez90:es-ES => vuejs-es:es-ES)

Recomiendo comenzar por [esta](https://github.com/vuejs-es/vuejs.org/blob/es-ES/src/v2/guide/) carpeta y crees un PR por cada archivo.

Dime si me dejo algo o precisas de mas informacion.

PD: no olvides revisar las [Pautas de traducción](https://github.com/vuejs-es/vuejs.org/wiki/Pautas-de-Traducci%C3%B3n).

**Comment by rgomez90** [comment]
Ok, perfecto. 

Ya me puse a ello.

Un par de preguntas:

* `Bindings` lo traducimos a `enlaces de datos`? (hecha un ojo a #49 )
* En los enlaces a páginas externas como por ej. `Mozilla Developer` ponemos el link **siempre** de la versión original de Vue Docs o si existe la misma página en español usamos ese?
* Quien(es) es/son los revisores en caso de existir?
* Seria posible actualizar/limpiar el proyecto si esta en mente seguir utilizandolo?
* Se ha barajado la posibilidad de usar algún sistema de localización? Por ej. [GitLocalize ](https://gitlocalize.com/pricing).

**Comment by miljan-aleksic** [comment]
- No se como traducir `bind`, seria bueno encontrar un ejemplo en alguna doc que lo utilize.
- Si, existe enlace en español me parece bien usarlo.
- Unicamente yo, al parecer...
- Sí, la idea es seguir adelante segun las posibilidades.
- Desconocia GitLocalize, parece interesante. Les he pedido una cuenta OSS, a ver.

**Comment by rgomez90** [comment]
* Data Bindings y bind se traduce a enlaces de datos y enlazar a
  * [Microsoft WPF Docs](https://docs.microsoft.com/es-es/dotnet/framework/wpf/data/data-binding-wpf)
  * [Blog Javi Suarez](https://javiersuarezruiz.wordpress.com/2011/07/17/data-binding-en-wpf-1%C2%BA-parte-introduccion/)
  * [Otro Blog](https://www.fullstack.pe/blog/angular-data-binding)

**Comment by miljan-aleksic** [comment]
A mi me parece bien no traducirlo.

**Comment by miljan-aleksic** [comment]
@rgomez90, @UchihaCFC, @juansaab. El master branch ha sido actualizado con las revisiones de @rgomez90, por lo que ahora podemos continuar todos desde el master y ceñirnos a el.

Tocaria revisar el master tomando como punto de referencia el branch 2.5 de la repo en Ingles, ya que es la version que estamos traduciendo. Por lo que cada uno escoga una seccion que pueda revisar. Dejo la lista a completar.

- [x] api
- [ ] cookbook
- [ ] examples
- [x] guide
- [ ] style-guide

@rgomez90 y @UchihaCFC revisaron recientemente las secciones api y guide, pero si dentro de las mismas falta algo, comentadlo.

**Comment by UchihaCFC** [comment]
De momento puedo revisar el de examples si queréis y luego tirar por style-guide, si @rgomez90 o @juansaab lo ven también bien.

Creo que el de cookbook va a ser el más pesado y podremos dividirlo más por partes.

**Comment by miljan-aleksic** [comment]
Chicos, el ultimo commit ha resultado ser erroneo, por lo que he vuelto al commit anterior. @rgomez90, cuando puedas revisamos de nuevo tu aporte.

**Comment by miljan-aleksic** [comment]
He reseteado las tareas en Projects, revisad las para ir asignando. @UchihaCFC, tienes asignado Examples.

**Comment by rgomez90** [comment]
> Chicos, el ultimo commit ha resultado ser erroneo, por lo que he vuelto al commit anterior. @rgomez90, cuando puedas revisamos de nuevo tu aporte.

Hoy tengo toda la tarde. Avisame y le damos

**Comment by miljan-aleksic** [comment]
@rgomez90 me va bien ahora, creas un chat como la otra vez?

**Comment by rgomez90** [comment]
@miljan-aleksic perdona que no me salto la notificacion de tu respuesta. Quizas lo mejor sea que habras un canal en [Gitter](https://gitter.im/home/explore#createcommunity) asociandolo con este repo. (Lo haria yo, pero al no ser collaborator del repo no puedo). Asi tendriamos un punto central para discutir "live". Si no, dime y creo uno temporal como ayer.

**Comment by miljan-aleksic** [comment]
Gitter es pesimo, ni siquiera me permite reabrir el canal entre otros. Cuando puedas:

1) elimina tu vuejs-es fork
2) crea el fork de nuevo
3) aplica tus cambios en el master asegurandote que ningun texto ya traducido es revertido (el problema que detecte antes)
4) abre el PR y seguimos comentando en el mismo

**Comment by UchihaCFC** [comment]
> He reseteado las tareas en Projects, revisad las para ir asignando. @UchihaCFC, tienes asignado Examples.

@miljan-aleksic Perfect, me pongo con eso en cuanto pueda y envío PR para revisión. ¿Lo hacemos por secciones dentro de examples como hicimos con la API o mejor todo junto?.

**Comment by miljan-aleksic** [comment]
@UchihaCFC, todo junto siempre y cuando el commit no sea excesivamente grande. Gracias ^^

**Comment by miljan-aleksic** [comment]
@rgomez90, viste mi comentario?

**Comment by mdxmtz** [comment]
Que tal, me gustaría participar, ¿con que podría ayudarles? Gracias

**Comment by miljan-aleksic** [comment]
Hola @mdxmtz, si te parece te asigno la traduccion de Cookbook, no es muy largo.

**Comment by mdxmtz** [comment]
@miljan-aleksic muy bien

**Comment by miljan-aleksic** [comment]
@mdxmtz, listo :)

**Comment by rgomez90** [comment]
@miljan-aleksic si lo he leido. Hoy hasta la noche estoy bastante ocupado. A ver si sobre las 22 tengo todo listo y te aviso.

**Comment by miljan-aleksic** [comment]
@rgomez90, se que andas liado pero crees que lo podrias tener listo esta semana?

**Comment by mdxmtz** [comment]
Aprovechando, ¿como traducirían? "We scope ...", por ejemplo en el siguiente enunciado: " We scope instance properties with $ to avoid this."

**Comment by UchihaCFC** [comment]
@mdxmtz pues esa frase es algo confusa para traducir, porque por scope en programación lo entendemos como el ámbito o entorno donde actuamos, al menos yo lo veo así. 

Tampoco tenemos una traducción genérica específica como para otras palabras, así que en este caso esa frase yo la dejaría en algo como: 'alcanzamos propiedades de instancia con $ para evitar esto', pero a ver qué dice el resto.

Si nos dices en qué parte de lo que estás traduciendo está, igual encontramos algo más acorde al contexto en el que esté.

**Comment by mdxmtz** [comment]
En [adding-instance-properties de cookbook](https://github.com/vuejs-es/vuejs.org/blob/master/src/v2/cookbook/adding-instance-properties.md), último párrafo de "The Importance of Scoping Instance Properties"
