### ISSUE TITLE
Términos Webhook y Hook

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#51]
Deberiamos traducir estos términos o no?

Segun veo por internet **Webhook** no se traduce en el español. [MailChimp](https://mailchimp.com/es/help/set-up-webhooks/)

Respecto a **Hook** he visto ambas: sin traducir ó **gancho/enganchar** pero me da la sensación que solo lo traducen, los paises sudamericanos. Las páginas españolas lo dejan en ingles.

El tema del castellano de España y de Sudamerica, es algo que quizas habria que controlar algo , ya que las diferencias no son pequeñas.

**Comment by miljan-aleksic** [comment]
Dejemoslo sin traducir. Hay que optar por el Español neutro, que segun entiendo seria el de España sin usar expresiones locales.

**Comment by rgomez90** [comment]
Pienso lo mismo.
