### ISSUE TITLE
Links a páginas

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#54]
Cual es la estrategia con los links?

Debemos traducir los links a otros documentos markdown o párrafos para que se ajusten a los titulos en espanol? Es decir 

`[Link](#Block-title) => [Link](#titulo-parrafo)`

Luego, en este tipo de links (https://vuex.vuejs.org/en/index.html) lo dejamos asi? 
Supongo que no tenemos un link para los docs en espanol? Pero dejandolo así, llevarían todos los links a la página inglesa....y eso no tiene mucho sentido...

**Comment by UchihaCFC** [comment]
Yo por el momento estaba dejando los links con la url tal y como vienen aunque traducía el title, pero tienes razón, quizá sería bueno que cuando nos toque pongamos la url pero con el /es/ porque imagino que cuando tengamos todo listo lo subirán a una url de ese tipo. ¿Qué os parece?. Aunque habría que revisar todos los links que haya por si acaso ...

**Comment by rgomez90** [comment]
Exacto, y de hacerlo lo mejor hacerlo cuanto antes, sino tocara repasar todos los links despues.

**Comment by UchihaCFC** [comment]
Podemos ponerlo como pauta en la wiki si todos estamos de acuerdo, creo que no está, good tip 👍

**Comment by miljan-aleksic** [comment]
Los links dejarlos relativos y con el ALT traducido, en el momento de la compilacion apuntaran a la version correcta.

Los links externos, como el de vuex `https://vuex.vuejs.org/en/index.html` o cualquier otro, comprobar si existe alternativa en Español y usarla.

Wiki actualizado.
