### ISSUE TITLE
Dueño repositorio / equipo

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#55]
@miljan-aleksic veo que tu no eres el dueño del repo ni del team.

De hecho veo que el dueño no anda muy activo...no sería mejor que lo pasases a tu propiedad? Si creciesemos un poco necesitaremos a alguien que tenga todos los derechos del repo, o los tienes tu ya?

**Comment by miljan-aleksic** [comment]
Tengo pleno acceso :)
