### ISSUE TITLE
Cambiar README

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#56]
@miljan-aleksic podemos cambiar el README o tenemos que dejarlo así?
Para añadir algo de información respecto a contribuir etc etc...

**Comment by miljan-aleksic** [comment]
Justamente estaba pensando como hacer para que quede en el history las colaboraciones. Por que ahora con la branch 2.5-es se perderian todos los commits de los colaboradores y pareceria que el trabajo fue hecho unicamente por unos pocos.

Lo que se me ocurre es que una vez tengas el Guide completo, hagas un vuelco total de esta carpeta a master y asi el history se queda intacto y por encima el tuyo.

Luego anadir ademas las colaboraciones en el readme, etc, me parece bien.

**Comment by rgomez90** [comment]
ok, perfecto podemos hacerlo así.

Por cierto te contestaron los de GitLocalize? Yo ayer probe con un repo mio de prueba y pude hacerlo sin problemas. Lo unico que te dan el plan "free" que tiene un limite de 1000 bloques texto. Si cambiar a plan Open Source (el q queremos) son 20000. 

Si quieres te paso el link del repo de la prueba y su pagina de gitlocalize para que lo pruebes un poco y ver como funciona antes de decidir si nos pasamos o no

**Comment by miljan-aleksic** [comment]
No me contestaron, pero terminemos la 2.5 como hasta ahora (al menos las secciones comenzadas) y lleguemos a algo terminado, antes de experimentar mas. Si quieres entonces me lo pasas que tendre mas tiempo, si no me contestaron todavia.
