### ISSUE TITLE
Event handler

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#58]
Veo que en la wiki traducimos esto a `manejador de eventos`. 

La traducción correcta en el mundo de la programación, al menos en España, es **Controlador de eventos** y **control de eventos** para event handling.

De hecho hace relativamente poco estuve en Madrid y Malagá en dos conferencias donde se utilizaban los términos asi traducidos. Ademas las grandes empresas lo traducen asi en sus docs.

Quizás en Sudamerica se traduzca así, pero creo q en toda mi vida, jamás escuche la palabra "manejador" y me suena sinceramente **fatal**.

Si estas de acuerdo @miljan-aleksic actualizo la wiki. 

Aparte creo que poner una "notita" con que **sintaxis es una palabra femenina - la sintaxis** no estaría de mas, puesto que en el 80% de los casos se tradujo como **el sintaxis**. De hecho en mi revisión estoy viendo mas elementos de Sudamerica que de España.

**Comment by juansaab** [comment]
@rgomez90 en realidad en latinoamérica no se usa "manejador de eventos" mucho menos "el sintaxis". Sospecho que alguien comenzó haciendo una traducción a lo _google translator_ porque al menos en lo que revisé ayer, habían unas traducciones muy literales.

+1 para "Controlador de eventos"

**Comment by miljan-aleksic** [comment]
Me parece bien, adelante :)

**Comment by rgomez90** [comment]
Ok. Wiki updated.
