### ISSUE TITLE
Traducción "unit test"

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#59]
Traducimos `unit test`? Si lo hacemos lo traducimos a `prueba unitaria`, que es lo que se ve como traducción por internet?

 Yo en mi opinión no lo traducía.

**Comment by miljan-aleksic** [comment]
Voto a no traducir. @juansaab, @UchihaCFC ?

**Comment by UchihaCFC** [comment]
Yo tampoco lo haría

**Comment by rgomez90** [comment]
Pues dado que @juansaab dió "thumbs-up" al comentario de @miljan-aleksic, tomo eso como que el también esta de acuerdo.

Asi que __unit test__ **NO** debe traducirse.

Actualizo Wiki y cierro el issue.
