### ISSUE TITLE
Traducción "bundle"

### ISSUE THREAD

**Issue by rgomez90** [vuejs-es/vuejs.org#60]
Otra pregunta, traducimos `bundle`? De hacerlo lo traducimos a `paquete` / `grupo` o cómo?

Un [ejemplo ](https://docs.microsoft.com/es-es/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)de la traducción de Microsoft

**Comment by miljan-aleksic** [comment]
Usa el ticket pautas de traduccion para este tipo de preguntas, alli se sigue el mismo hilo.

**Comment by rgomez90** [comment]
Ok, disculpa.
