### ISSUE TITLE
Traducción de "Built-In" 

### ISSUE THREAD

**Issue by juansaab** [vuejs-es/vuejs.org#61]
¿Alguna sugerencia de traducción para la expresión "Built-In Directives"? Se me ocurre "Directivas incluídas", "Directivas nativas".

**Comment by miljan-aleksic** [comment]
O Directivas incorporadas, aunque nativas tambien suena ok. @rgomez90, @UchihaCFC ?

**Comment by rgomez90** [comment]
Yo pienso que nativas e incluídas ambas suenan bien y son sinónimos.

**Comment by miljan-aleksic** [comment]
Lo dejamos en nativas. @juansaab, actualizas el wiki?

**Comment by juansaab** [comment]
Hecho!
