### ISSUE TITLE
No traducir "Debouncing"

### ISSUE THREAD

**Issue by juansaab** [vuejs-es/vuejs.org#62]
Me cuesta encontrar una buena alternativa para _debouncing_ en frases como:

> Debouncing is used to limit how often we execute Ajax requests and other expensive operations.

Creo que deberíamos dejarla sin traducir. ¿Qué opinan? @miljan-aleksic @rgomez90 @UchihaCFC

**Comment by rgomez90** [comment]
Yo en mi carrera (en Alemania) lo he oído muchas veces en el ámbito de la electrónica. Aunque en alemán sí que hay una traducción, que no se usa demasiado( se suele usar __debounce__), cuando he leido algun libro, artículo, etc. en castellano y me he encontrado con la palabra, **nunca**, que recuerde,  lo ví traducido.

**Comment by miljan-aleksic** [comment]
Termino no traducible :)
